using System;
using System.IO;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MimeKit;
using MailKit;
using MailKit.Net.Smtp;
using MailKit.Net.Imap;
using MailKit.Search;
using Microsoft.Agents.AI;

namespace CodingAgents.Server.Services;

public class EmailService
{
    private readonly string _smtpServer;
    private readonly int _smtpPort;
    private readonly string _imapServer;
    private readonly int _imapPort;
    private readonly string _username;
    private readonly string _password;
    private readonly string _targetEmail;

    private readonly bool _isEnabled;

    public EmailService(EmailConfig config)
    {
        if (string.IsNullOrEmpty(config.SmtpServer) || 
            string.IsNullOrEmpty(config.ImapServer) || 
            string.IsNullOrEmpty(config.Username) || 
            string.IsNullOrEmpty(config.Password) || 
            string.IsNullOrEmpty(config.TargetEmail))
        {
            _smtpServer = string.Empty;
            _imapServer = string.Empty;
            _username = string.Empty;
            _password = string.Empty;
            _targetEmail = string.Empty;
            _isEnabled = false;
            Console.WriteLine("[EmailService] WARNING: Email configurations are incomplete. Service is disabled.");
        }
        else
        {
            _smtpServer = config.SmtpServer;
            _smtpPort = config.SmtpPort;
            _imapServer = config.ImapServer;
            _imapPort = config.ImapPort;
            _username = config.Username;
            _password = config.Password;
            _targetEmail = config.TargetEmail;
            _isEnabled = true;
        }
    }

    public async Task SendNotificationAsync(string subject, string body)
    {
        if (!_isEnabled)
        {
            Console.WriteLine("[EmailService] Notification not sent: Service is disabled.");
            return;
        }
        try
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("Claude C# Agent", _username));
            // REPLACE WITH: the display name you want on notification emails.
            message.To.Add(new MailboxAddress("User", _targetEmail));
            message.Subject = subject;

            message.Body = new TextPart("plain")
            {
                Text = body
            };

            using var client = new SmtpClient();
            // Use SSL/TLS
            await client.ConnectAsync(_smtpServer, _smtpPort, true);
            await client.AuthenticateAsync(_username, _password);
            await client.SendAsync(message);
            await client.DisconnectAsync(true);

            Console.WriteLine($"[EmailService] Notification sent: {subject}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[EmailService] Error sending email: {ex.Message}");
        }
    }

    public async Task PollInboxAndExecuteAsync(AIAgent agent)
    {
        if (!_isEnabled)
        {
            return;
        }
        try
        {
            using var client = new ImapClient();
            await client.ConnectAsync(_imapServer, _imapPort, true);
            await client.AuthenticateAsync(_username, _password);

            var inbox = client.Inbox;
            await inbox.OpenAsync(FolderAccess.ReadWrite);

            // Search for unread messages from the authorized user
            var query = SearchQuery.NotSeen.And(SearchQuery.FromContains(_targetEmail));
            var uids = await inbox.SearchAsync(query);

            foreach (var uid in uids)
            {
                var message = await inbox.GetMessageAsync(uid);
                string subject = message.Subject ?? "No Subject";

                // Get the prompt text. PlainText is preferred.
                string prompt = message.TextBody ?? message.HtmlBody ?? "";

                // Strip email replies/thread history if any, to only get the actual new command
                prompt = CleanEmailBody(prompt);

                if (string.IsNullOrWhiteSpace(prompt))
                    continue;

                Console.ForegroundColor = ConsoleColor.Magenta;
                Console.WriteLine($"\n[EmailService] RECEIVED EMAIL PROMPT: \"{prompt}\"");
                Console.ResetColor();

                // Mark as seen immediately so we don't process it again if execution is slow
                await inbox.AddFlagsAsync(uid, MessageFlags.Seen, true);

                // Run the prompt through our C# Agent!
                string responseText;
                try
                {
                    var response = await agent.RunAsync(prompt);
                    responseText = response.Text ?? "No text response generated by the agent.";
                }
                catch (Exception ex)
                {
                    responseText = $"Error executing agent prompt: {ex.Message}\n{ex.StackTrace}";
                }

                // Send the response back via SMTP!
                string replySubject = subject.StartsWith("Re:", StringComparison.OrdinalIgnoreCase) ? subject : $"Re: {subject}";
                await SendNotificationAsync(replySubject, responseText);
            }

            await client.DisconnectAsync(true);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[EmailService] Error polling inbox: {ex.Message}");
        }
    }

    private string CleanEmailBody(string body)
    {
        var lines = body.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        var cleanLines = new List<string>();

        foreach (var line in lines)
        {
            var trimmed = line.Trim();
            // Stop parsing if we hit email signature or quoting headers
            if (trimmed.StartsWith(">") || 
                trimmed.StartsWith("-----Original Message-----") || 
                trimmed.StartsWith("From:") && cleanLines.Count > 0 ||
                trimmed.StartsWith("On ") && trimmed.Contains("wrote:") && cleanLines.Count > 0)
            {
                break;
            }
            cleanLines.Add(line);
        }

        return string.Join(Environment.NewLine, cleanLines).Trim();
    }
}
